name: Lisflood Utilities Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall build-essential
        sudo apt-get install libstdc++6
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get dist-upgrade
        conda install -c conda-forge python=3.7 libgcc-ng gdal==3.5.0 eccodes 
        pip install -r requirements.txt
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        gdal-config --version
        pip list
        conda list
        python -c "from osgeo import gdal; print(gdal.__version__)"
        conda install -c conda-forge pytest pytest-cov
        pytest
