name: Lisflood Utilities using env file and ubuntu-20.04

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Update build essential
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall build-essential
    - name: Install dependencies
      run: |
        conda install -c conda-forge gdal --name base
        conda install -c conda-forge eccodes --name base
    - name: Test with pytest
      run: |
        conda install pytest pytest-cov
        pip install -r requirements.txt
        pytest
