name: Lisflood Utilities using env file and ubuntu-20.04

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda create --name myenv python=3.7 -c conda-forge
    - name: Install dependencies
      run: |
        conda activate myenv
        conda install -c conda-forge gdal==3.5.0 eccodes
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        gdal-config --version
        pip list
        python -c "from osgeo import gdal; print(gdal.__version__)"
        conda install -c conda-forge pytest pytest-cov
        pytest
